version: 2
updates:
  - package-ecosystem: "docker"
    directories: 
    - "/base-images/*" # scan Dockerfiles under base-images/
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

# last-touch: 2025-10-25T12:20:46Z
