name: Trigger Dependabot by touching dependabot.yml

on:
  schedule:
    - cron: '0 * * * *'     # every hour at minute 0 — change to daily/weekly if preferred
  workflow_dispatch: {}     # allow manual run

permissions:
  contents: write
  pull-requests: write

jobs:
  touch-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Touch .github/dependabot.yml to trigger Dependabot
        env:
          FILE: .github/dependabot.yml
        run: |
          if [ ! -f "$FILE" ]; then
            echo "ERROR: $FILE not found"
            exit 1
          fi

          TIMESTAMP="# last-touch: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          if grep -q '^# last-touch:' "$FILE"; then
            sed -i "s|^# last-touch:.*|$TIMESTAMP|" "$FILE"
          else
            echo "" >> "$FILE"
            echo "$TIMESTAMP" >> "$FILE"
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$FILE"

          if git diff --cached --quiet; then
            echo "No change to $FILE; nothing to commit."
          else
            git commit -m "chore: touch dependabot.yml to trigger Dependabot run [skip ci]"
            git push origin chore/trigger-dependabot
            echo "Pushed touch commit to trigger Dependabot."
          fi